### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by adamltyson**

### CODE REVIEW

**Comment by adamltyson** [comment]
Happy with an MIT license @dstansby & @paddyroddy?

**Comment by paddyroddy** [comment]
> Happy with an MIT license @dstansby & @paddyroddy?

Licensing is one of these things that I know I should know, but every time I have to do something, I have to look it up again. Deferring to @dstansby

**Comment by adamltyson** [comment]
MIT is basically fully open-source, do what you like. It's what we've chosen for all BG stuff unless there are other factors at play. Just wanted to check with both of you before I applied it here (as you wrote everything in the first place!).

**Review by dstansby — APPROVED** [review]
👍 from me

**Pull request merged**
